### ISSUE TITLE
crash on partial_le(&mins, &maxs) assert when updating collision_world

### ISSUE THREAD

**Issue by arturoc** [sebcrozet/ncollide#146] opened 2017-03-20 18:02 UTC
here's the stacktrace:

```
thread 'main' panicked at 'assertion failed: na::partial_le(&mins, &maxs)', /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.3.0/bounding_volume/aabb.rs:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <ncollide_geometry::bounding_volume::aabb::AABB<P>>::new
             at ./<panic macros>:3
   1: ncollide_geometry::bounding_volume::aabb_utils::support_map_aabb
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.3.0/bounding_volume/aabb_utils.rs:29
   2: ncollide_geometry::bounding_volume::aabb_support_map::<impl ncollide_geometry::bounding_volume::bounding_volume::HasBoundingVolume<M, ncollide_geometry::bounding_volume::aabb::AABB<P>> for ncollide_geometry::shape::triangle::Triangle<P>>::bounding_volume
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.3.0/bounding_volume/aabb_support_map.rs:32
   3: ncollide_geometry::bounding_volume::aabb::aabb
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.3.0/bounding_volume/aabb.rs:15
   4: ncollide_geometry::shape::shape_impl::<impl ncollide_geometry::shape::shape::Shape<P, M> for ncollide_geometry::shape::triangle::Triangle<P>>::aabb
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.3.0/shape/shape_impl.rs:39
   5: ncollide_geometry::bounding_volume::aabb_shape::<impl ncollide_geometry::bounding_volume::bounding_volume::HasBoundingVolume<M, ncollide_geometry::bounding_volume::aabb::AABB<P>> for ncollide_geometry::shape::shape::Shape<P, M> + 'static>::bounding_volume
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.3.0/bounding_volume/aabb_shape.rs:8
   6: ncollide_geometry::bounding_volume::aabb::aabb
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.3.0/bounding_volume/aabb.rs:15
   7: <ncollide_pipeline::narrow_phase::contact_generator::composite_shape_shape_contact_generator::CompositeShapeShapeContactGenerator<P, M>>::do_update
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_pipeline-0.10.0/narrow_phase/contact_generator/composite_shape_shape_contact_generator.rs:41
   8: <ncollide_pipeline::narrow_phase::contact_generator::composite_shape_shape_contact_generator::ShapeCompositeShapeContactGenerator<P, M> as ncollide_pipeline::narrow_phase::contact_generator::contact_generator::ContactGenerator<P, M>>::update
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_pipeline-0.10.0/narrow_phase/contact_generator/composite_shape_shape_contact_generator.rs:159
   9: <ncollide_pipeline::narrow_phase::contact_generator::composite_shape_shape_contact_generator::CompositeShapeShapeContactGenerator<P, M>>::do_update::{{closure}}
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_pipeline-0.10.0/narrow_phase/contact_generator/composite_shape_shape_contact_generator.rs:79
  10: <ncollide_geometry::shape::trimesh::TriMesh<P> as ncollide_geometry::shape::composite_shape::CompositeShape<P, M>>::map_transformed_part_at
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.3.0/shape/trimesh.rs:99
  11: <ncollide_pipeline::narrow_phase::contact_generator::composite_shape_shape_contact_generator::CompositeShapeShapeContactGenerator<P, M>>::do_update
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_pipeline-0.10.0/narrow_phase/contact_generator/composite_shape_shape_contact_generator.rs:73
  12: <ncollide_pipeline::narrow_phase::contact_generator::composite_shape_shape_contact_generator::CompositeShapeShapeContactGenerator<P, M> as ncollide_pipeline::narrow_phase::contact_generator::contact_generator::ContactGenerator<P, M>>::update
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_pipeline-0.10.0/narrow_phase/contact_generator/composite_shape_shape_contact_generator.rs:123
  13: <ncollide_pipeline::narrow_phase::default_narrow_phase::DefaultNarrowPhase<P, M> as ncollide_pipeline::narrow_phase::narrow_phase::NarrowPhase<P, M, T>>::update
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_pipeline-0.10.0/narrow_phase/default_narrow_phase.rs:49
  14: <ncollide_pipeline::world::collision_world::CollisionWorld<P, M, T>>::perform_narrow_phase
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_pipeline-0.10.0/world/collision_world.rs:218
  15: <ncollide_pipeline::world::collision_world::CollisionWorld<P, M, T>>::update
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_pipeline-0.10.0/world/collision_world.rs:84
  16: blender_example::world::World::update
             at ./src/world.rs:261
```

i'm using a trimeshes for the shapes and all are complex models so it's difficult to upload an example but will try to reproduce it with something simpler if this doesn't give you any clue.

also it only crashes some times with the exact same data so it's probably some precision problem or similar.

**Comment by sebcrozet** [comment] 2017-03-20 23:08
Mmh, this typically happens when the input data (vertices) contains `NaN`. But I guess this is not the case here. But unless your triangle mesh is very thin (i.e. close to having no thickness), I don't think this can be a precision problem. A simpler case could be useful to understand this indeed.

If you cannot reproduce it, perhaps you could compile your project in debug, and print the values of `mins` and `maxs` that make the assertion fail? This would help a lot!

**Comment by sebcrozet** [comment] 2018-06-14 15:01
Closing this since it may be related to #188 or #182 which are both fixed. Please reopen with more details if the issue persists.

**Closed by sebcrozet** 2018-06-14 15:01 UTC
Labels: bug
